version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=/app/data/e2e_tests.db
      - HEADLESS=true
      - TIMEOUT=30000
    volumes:
      - app_data:/app/data
      - screenshots:/app/screenshots
    restart: unless-stopped
    networks:
      - e2e_network

  # 開発用リバースプロキシ（オプション）
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - e2e_network
    profiles:
      - production

volumes:
  app_data:
    driver: local
  screenshots:
    driver: local

networks:
  e2e_network:
    driver: bridge 